# -*- coding: utf-8 -*-
"""PortafolioModulo2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12hwiG6Pj6AtFDY-uKAiG3rpwXTQrIV0k
"""

# Regresion lineal simple.

# Valores de Calificaciones (Int) y promedios (float).
calificaciones = [87,90,97,98,94,91,60,70,90,75,89,87,90,99,98,90]
promedios = [90.50,100,86.5,70.7,90.10,89,87.53,99.3,94.3,70.8]

# Calcular media.
def mean(values):
    return sum(values) / len(values)

# Calcula la suma de los productos cruzados y la suma de los cuadrados de las calificaciones.
desviacion_cruzada = 0
desviacion_cuadrado_calificaciones = 0
media_calificaciones = sum(calificaciones) / len(calificaciones)
media_promedios = sum(promedios) / len(promedios)

for index, yi in zip(calificaciones, promedios):
    # Calcula la desviación cruzada entre la calificación y el promedio correspondiente.
    desviacion_cruzada += (index - media_calificaciones) * (yi - media_promedios)
    # Calcula la desviación al cuadrado de la calificación.
    desviacion_cuadrado_calificaciones += (index - media_calificaciones) ** 2

# Calcular coeficientes de la regresión lineal.
pendiente = desviacion_cruzada / desviacion_cuadrado_calificaciones
independiente = media_promedios - pendiente * media_calificaciones

# Imprimir coeficientes.
print("Coeficiente de Pendiente:", pendiente)
print("Término Independiente:", independiente)

# Función para hacer predicciones.
def predict(prediccion):
    return pendiente * prediccion + independiente

# Realiza una predicción.
prediccion_calificaciones = 18
prediccion_promedios = predict(prediccion_calificaciones)
print("Predicción para calificaciones =", prediccion_calificaciones, ":", prediccion_promedios)

"""Bueno lo primero que hacemos es definir dos matrices unidimensionales (calificaciones y promedios), despues definimos una funcion "mean()" que nos ayuda a calcular la media de calificaciones y promedios y las almacenamos en dos variables llamadas media_calificaciones y media_promedios.

Despues calculamos la suma de los productos cruzados y la suma de los cuadrados de las calificacioens en dos variables, desviacion_cruzada y desviacion_cuadrado_calificaciones, se inicia un ciclo for donde vamos a recorrer las listas de calificacioens y promedios y en cada iteracion vamos calculando la desviacion cruzada entre las calificacioens y el promedio, y su suma de las 3 la almacenamos en la variable desviacion_cruzada, asi mismo tambien calculamos la desviacio nal cuadrado de las calificaciones en base a su media, las sumamos y las almacenamos en la variable desviacion_cuadrado_calificaciones.

Despues de acabar el for calculamos la pendiente de la regresion lineal dividiendo la desviacion_cruzada entre la desviacion_cuadrado_calificaciones, despues calculamos el termino independiente de la regresion lineal simple haciendo la resta del producto de la pendiente y la media de calificaciones de la media de promedios, despues imprimimos en pantalla los coeficientes de la regresion lineal (la pendiente y el termino independiente), finalmente definimos una funcion predict() que insertamos el valor de prediccion y para realizar la prediccion utilizamos la pendiente y el termino independiente, asi mismo por ultimo realizamos la prediccion para los valores de calificaciones que son 18 valores y utilizamos la funcion predict() e imprimimos el resultado.
"""